### ISSUE TITLE
Puppet Could not find resources auditd

### ISSUE THREAD

**Issue by eloyacosta** [kemra102/puppet-auditd#14] opened 2016-08-05 20:55 UTC
I got that error. 

> Warning: Could not find resource 'Concat[audit-file]' in parameter 'before'
>    (at /etc/puppetlabs/code/modules/auditd/manifests/init.pp:446)
> Warning: Could not find resource 'Package[auditd]' in parameter 'require'
>    (at /etc/puppetlabs/code/modules/auditd/manifests/audisp/syslog.pp:10)

My guess is that for whatever reason the variables on params.pp are not getting substituted 

```
case $::osfamily {

[..] 

 case $::lsbmajdistrelease {
        '8': {
          $service_restart = '/bin/systemctl restart auditd'
          $service_stop    = '/bin/systemctl stop auditd'
        }
        default: {
          $service_restart = '/etc/init.d/auditd restart'
          $service_stop    = '/etc/init.d/auditd stop'
        }
      }
    }
    'Suse': {
      $package_name       = 'audit'
      $audisp_package     = 'audispd-plugins'
      $manage_audit_files = false
      $rules_file         = '/etc/audit/audit.rules'
      $service_restart    = '/etc/init.d/auditd restart'
      $service_stop       = '/etc/init.d/auditd stop'
    }
    'RedHat': {
      $package_name       = 'audit'
      $audisp_package     = 'audispd-plugins'
      $manage_audit_files = true

[..] 
```

I'm using puppet apply on a RHEL 6 box. 

```
fact =>
osfamily => RedHat
```

Thanks!

**Comment by seanscottking** [comment] 2016-10-12 18:19
+1, I only started seeing this when I started playing with Puppet 4.

My error (warning, really) looks like this:

```
==> default: Warning: Could not find resource 'Concat[audit-file]' in parameter 'before'
==> default:    (at /tmp/vagrant-puppet/modules-403548b863500d05a9294cc01c72d95b/auditd/manifests/init.pp:446)
```

I'll try to do some more research and send a PR.

**Comment by kemra102** [comment] 2016-11-24 23:43
I managed to test this in Vagrant on CentOS 6.6 with puppet `4.3.2` but couldn't reproduce the issue, is it still a problem for you guys?

**Comment by kemra102** [comment] 2016-12-29 10:55
It's been a few weeks so I'm going to close this issue for now. Please feel free to re-open if you need to do so.

**Closed by kemra102** 2016-12-29 10:55 UTC
